url: "https://dlyang.me"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 15
permalink: /:title

# For RSS xml
title: LanternD's Castle
description: － Survive Technically －
feed: /rss.xml
author_info: <a href="https://dlyang.me/">LanternD</a>

# Author info. Please update them accordingly.
author:
  name: LanternD
  email: lanternd1028@gmail.com
  link: https://dlyang.me/
  github: https://github.com/LanternD
  instagram: https://instagram.com/lantern_d
  youtube: https://www.youtube.com/channel/UCPAJ2XwlkmbCvVZ-asjfi3w
  flickr: https://www.flickr.com/photos/lanternd
  px500px: https://500px.com/lanternd
  telegram: https://telegram.me/lanternd
  mastodon: https://t.dlyang.me

# Image host prefix
img-hosting: https://img-cdn.dlyang.me

# Gavatar and favicon
gavatar: /img/logo_100x.png
favicon: /img/favicon2.ico

# Google analytics
ga:
  id: UA-54601036-1
  url: https://dlyang.me
  userid: 54601036

# Disqus ID
disqus:
  shortname: lanternd

# Jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - rouge

# For sitemap.txt
production_url: https://dlyang.me

sass:
  load_paths:
    - _sass
    - node_modules
  sass_dir: _sass
  style: expanded
  sourcemap: development
